containers/bubblewrap

bubblewrap.c

The option is called --seccomp, so don't complain about --seccomp-fd
in the error message.

Fix a typo

---

bind-mount.c
bubblewrap.c
bwrap.xml
completions/bash/bwrap

This allows to remount a mount point as read only.
It will allow us, by remounting / after other mount points are created,
to handle a readonly rootfs as specified in the OCI specs:
https://github.com/opencontainers/runtime-spec/blob/master/config.md#root-configuration
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
```
$ bwrap --bind rootfs / --tmpfs /tmp --remount-ro / touch /tmp/a
$ bwrap --bind rootfs / --tmpfs /tmp --remount-ro / touch /a
touch: cannot touch '/a': Read-only file system
```

Add --remount-ro DEST

---

bubblewrap.c
bwrap.xml

--block-fd is used to block execution of the child process, while --info-fd returns the pid of the container process (can be extended to export more information, if needed).

Add `--block-fd` and `--info-fd` so to be able to manage OCI hooks.

---

bubblewrap.c
bwrap.xml
completions/bash/bwrap
tests/test-run.sh

Useful to run a process with PID=1
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

bubblewrap: add --as-pid-1

---

bubblewrap.c
bwrap.xml
tests/libtest-core.sh
tests/test-run.sh
utils.c
utils.h

The end goal for this work is to run chrome in a flatpak, using the self-sandboxing portal. For this we want to be able to have the portal spawn a new sandbox with limited pid & fs & network access, yet have the requesting pid (the main chrome process) see these new pids.
To do this we add a new --userns feature to bwrap where it can reuse and existing user namespace for getting capabilities and then --pidns that allows bwrap to reuse an existing pid namespace. We'll use both --pidns and --unshare-pid which means that first enter the old pid namespace, but then create a new pid namespace as a child of that.
Fundamentally this should be workable with the setuid mode, at least when user namespaces are supported, however for technical reasons I was not able to do that (see commit comments) …

Support for reusing namespaces

---

bubblewrap.c

In the non-setuid case if we're not running as uid 0 in the final
namespace but we need devpts (e.g. use --dev) we mount the devpts as
uid and then change to the actual numberical uid at the end. This
final unshare(CLONE_NEWPID) will reset tha cap bounding set we
previously cleared.
This change clears the cap bounding set again after the unshare call.
This is not really a security problem because we always set
NO_NEW_PRIVS which is essentially a superset of capability bounds, so
there is no way the container can use the bounding set to gain
caps. However its nice to be consistent and not display setting
which look like potential problems.
Fixes https://github.com/containers/bubblewrap/issues/350
See 6b3dd4f10c23f23a2f3c3ec0f0d27ffc1149194c for the original change
the drops the cap …

Ensure we're always clearing the cap bounding set

---

tests/test-run.sh

This should fix #353 by checking one of two different pattern sets, based on the installed capsh version.

tests: Update output patterns for libcap >= 2.29

---

bind-mount.c
bubblewrap.c

There's an effort to migrate Linux filesystems to handle the y2038
problem, which is great.  However, recently a kernel change landed
that emits a warning when mounting a filesystem that doesn't
handle it, and this notably shows up even when *remounting* e.g.
for a read-only bind mount:
Using e.g. `rpm-ostree install cowsay` there's a spam of:
```
[  189.529594] xfs filesystem being remounted at /sysroot supports timestamps until 2038 (0x7fffffff)
```
Now particularly when creating a our bind mounts, let's
ask the kernel to be quiet about it.  This is not a major event
worthy of a kernel log.

Add MS_SILENT to most mount() invocations

---

tests/test-run.sh

This test runs Bubblewrap in a pid namespace with `/proc` for the parent namespace. As a result Bubblewrap fails with an error in `namespace_ids_read` unless there is a process with pid 3 in the parent namespace.
Test with: `unshare -rpfm --mount-proc make check`
Also the test fails when run sudo root if root does not have permission to access the path of `test-bwrap`, I fix this by using `/proc/self/exe` to run nested `bwrap`.

Fix broken test

---

bubblewrap.c

This is required to work in a Docker container.

Accept EROFS for access() check of /proc entries

---

bubblewrap.c
tests/test-run.sh

If two mount namespaces can both see a directory, and we bind-mount a
non-directory into that directory, we have to create a non-directory
to mount it onto:
$ ls -l ~/tmp/mountpoint
ls: cannot access '/home/smcv/tmp/mountpoint': No such file or directory
$ bwrap --bind / / --bind /etc/os-release ~/tmp/mountpoint true
$ ls -l ~/tmp/mountpoint
-rw-rw-rw- 1 smcv smcv 0 Feb 16 10:27 /home/smcv/tmp/mountpoint
The mount point is currently created as an empty world-writable file,
but this doesn't seem like a least-astonishment thing to do.
Create it with read-only permissions instead, to make it clearer that
it's just a placeholder and prevent other users from filling it.
Resolves: https://github.com/containers/bubblewrap/issues/337

Create files as mount points with read-only permissions

---

.github/workflows/block-autosquash-commits.yml
.github/workflows/check.yml
Makefile.am
ci/builddeps.sh
tests/libtest-core.sh
tests/test-run.sh

* build: Make sure test-bwrap is executable
* libtest-core: On failure, make it clearer what has happened
If we fail as a result of `set -x`, It's often not completely obvious
which command failed or how. Use a trap on ERR to show the command that
failed, and its exit status.
(Similar to ostreedev/ostree#2350)
* tests: Add a way to assert that bwrap is fully supported
If we're running on an operating system configuration where bwrap is
expected to work (unprivileged user namespace creation is allowed,
not in a chroot, not in a container, etc.), run with BWRAP_MUST_WORK=1.
* Add CI using Github workflows
Loosely based on the configuration used in Flatpak.

Add CI using Github workflows

---

tests/test-run.sh
utils.c

Previously, mounting a socket over the top of an existing socket
would fail, because create_file() opens it with creat():
$ test -e /run/systemd/resolve/io.systemd.Resolve && echo exists
exists
$ bwrap \
--bind / / \
--bind /run/systemd/resolve/io.systemd.Resolve \
/run/systemd/resolve/io.systemd.Resolve \
/bin/true
bwrap: Can't create file at /run/systemd/resolve/io.systemd.Resolve: No such device or address
Tolerate the file existing as any type that we will be able to mount
a non-directory onto.

Don't require mount point for a non-directory to be a regular file

---

tests/test-run.sh

The code supports this today, so test it.
xref https://github.com/containers/bubblewrap/pull/426
where I thought it didn't.

tests: Use --args multiple times

---

configure.ac

bubblewrap uses pkg-config to find e.g. the selinux libraries.
pkg-config itself is not looked for if the path for the bash
completions is given by command line.
this call makes sure that pkg-config is found either way.
downstream bug: https://bugs.gentoo.org/674312

ensure pkg-config is found

---

bwrap.xml

Detected by Debian's Lintian tool.

Fix typos for "descendant" in man page

---

bubblewrap.c
bwrap.xml
tests/test-run.sh

Based on #405 to avoid conflicts in `test-run.sh`, but could be separated if maintainers object to #405 for some reason.
* Implement --perms and --chmod
This allows files and directories created programmatically by bubblewrap
to be made less permissive (as requested in #346) or more permissive
(as requested in #131 and #329).
Resolves: https://github.com/containers/bubblewrap/issues/131
Resolves: https://github.com/containers/bubblewrap/issues/329
Resolves: https://github.com/containers/bubblewrap/issues/346

Implement --perms and --chmod

---

ci/builddeps.sh

Merging #344 made this unnecessary.

Stop installing python-is-python2 for CI

---

bind-mount.c
bubblewrap.c
utils.c
utils.h

If we are using a case-insensitive filesystem the bind-mount operation
might fail when `/proc/self/mountinfo` is checked.
In a case-insensitive filesystem, if we ask to mount a certain
directory, e.g. '/CI_fs/foo', the kernel might add its entry in
`mountinfo` as '/CI_fs/FOO'. This happens because the kernel populates
`mountinfo` with whatever case combination first appeared in the dcache.
With this patch we open the requested path and look at its
`/proc/self/fd`, using readlink(), to get the path case combination that
the kernel is also expected to be using.
---
/cc @smcv
A reproducer for this issue is:
```
mkdir /media/CI_dir
chattr +F /media/CI_dir  # Set directory as case-insensitive
mkdir /media/CI_dir/my_dir
echo 3 >  /proc/sys/vm/drop_caches  # Drop dcache
ls /media/CI_dir/MY_DIR …
```

Add support for bind-mount on case-insensitive filesystems

---

bubblewrap.c
tests/test-run.sh
utils.c
utils.h

* test-run: Test --setenv, --unsetenv
* Add --clearenv option
This allows environment variables to be set when running bwrap itself
(perhaps a custom LD_LIBRARY_PATH), but cleared for the command that
runs in the container, without having to enumerate all the variables.
Because PWD is set later, as a side-effect of changing directory, this
actually clears everything except PWD.
A portable program would check for clearenv() (and if not found, fall
back to using environ = NULL), but bubblewrap is Linux-specific, and
Linux C libraries (at least glibc and musl) do have clearenv().

Add --clearenv option

---

configure.ac
utils.c

security_context_t has always been a typedef for `char *` and used more
or less interchangeably with `char *`, but the use of a typedef turned
out to be bad for const-correctness. The function signatures were
changed to take `const char *` in libselinux 2.3, in 2014[1] and the
typedef was formally deprecated in 2020[2].
On very old OSs like Ubuntu 14.04, reinstate the casts to suppress
warnings from -Wdiscarded-qualifiers.
[1] https://github.com/SELinuxProject/selinux/commit/9eb9c9327563
[2] https://github.com/SELinuxProject/selinux/commit/7a124ca27581
---
bubblewrap is compiled with SELinux support on Debian but the majority of Debian systems don't use SELinux, so I'd appreciate it if a user of SELinux-based distros like Red Hat/Fedora could test this.
Marked as draft for now until I try …

utils: Remove security_context_t casts for libselinux >= 2.3

---

Makefile.am
tests/test-utils.c

This vaguely mimics GLib's GTest framework, but is self-contained.
---
I added this because I was working on a branch that added new utility code, but that branch turned out to be a dead end.
Having the framework seems useful anyway, and I think having a test for `has_path_prefix()` is maybe something we want?

Add a simple unit test for utility code

---

bind-mount.c
bind-mount.h
bubblewrap.c
configure.ac

* build: Error if a switch lacks a default case
This is a useful way to detect bugs before they happen.
* Handle all enum values in switch
This makes it clearer that we have thought about whether they need
symlinks for source resolved, and come to the conclusion that they do not.
* build: Warn if a switch over an enum does not handle all values
This is a useful way to catch possibilities being unhandled.
* bind_mount: Return an error code, and provide a way to display it
This gives us better diagnostic messages on failure, particularly for
BIND_MOUNT_ERROR_FIND_DEST_MOUNT where we previously said "Invalid
argument".
* bind-mount: Factor out bind_mount_result_to_string()

bind_mount: Return an error code, and provide a way to display it

---

bubblewrap.c
bwrap.xml
completions/bash/bwrap

New options introduced in #406, #401 weren't consistently added to all the places that list options.
The zsh completion deliberately isn't included in this PR: I have more changes that I want to make there (see #437).
* Document --chmod in --help
* Document --clearenv in man page
* bash: Include new options in completions
* bash: Sort completions in LC_ALL=C order
Where the order doesn't matter, a deterministic order minimizes
conflicts.

Add new options to documentation and bash completion

---

completions/bash/bwrap

bash completions are sourced, not executed, so this doesn't need to be
an executable script.

completions: Don't start bash completion with #!

---

configure.ac

This copy/paste from bash could end up installing into "$(DESTDIR)yes",
which is not as intended.

build: Fix installation of zsh completions in user-specified directory

---

Makefile.am
tests/libtest.sh
tests/test-run.sh
tests/test-specifying-pidns.sh
tests/test-specifying-userns.sh

* tests: Don't corrupt TAP output
Cater for strict TAP parsers by not printing random strings on stdout;
either direct them to stderr or to /dev/null, or turn them into TAP
diagnostics by prefixing "# ".
Automake has a relatively lenient TAP parser, but Meson has a more strict
TAP parser, so this is a prerequisite for adding a Meson build system.
* Extract some common test setup into libtest.sh
This will allow test-run.sh to be split up into more/smaller scripts.
* tests: Quote more defensively
* tests: Remove unnecessary nesting
* libtest: Add directive and 'set -e' for better shellcheck diagnostics
* tests: Really clean up test temporary directory
The flag file we create and the flag file we check for were not in sync.
Also similarly correct the variable name in an info message.
* …

Improve test-run.sh

---

bubblewrap.c

Unfortunately it's possible for argc to be 0, so error out pretty early
on in that case. I don't think this is a security issue in this case.

Handle argc == 0 better

---

.github/workflows/check.yml
completions/bash/meson.build
meson.build
meson_options.txt
tests/meson.build
tests/test-specifying-pidns.sh
tests/test-utils.c

Looks like #432 was less complete than I had intended, sorry.
Successfully tested on Debian 10, Ubuntu 20.04, Debian 11 and Debian unstable.
---
* meson.build: Remove unnecessary check for sh
* meson: Build tests with equivalent of -I$(top_srcdir) -I$(top_builddir)
* meson: Build the try-syscall helper
* meson: Run the Python test script with Python, not bash
The python build option can be used to swap to a different interpreter,
for environments like the Steam Runtime where the python3 executable in
the PATH is extremely old but there is a better interpreter available.
This is treated as non-optional, because Meson is written in Python,
so the situation where there is no Python interpreter at build-time
shouldn't arise.
* meson: Make G_TEST_SRCDIR, G_TEST_BUILDDIR match Autotools
* …

Fix Meson build system to be able to run tests

---

bubblewrap.c

`--help` shows `--add-seccomp` instead of `--add-seccomp-fd` which is the
correct argument.

Fix --add-seccomp-fd argument name in usage

---

README.md

Right now this link just opens a "path not found" page, so let's fix that by linking to the last commit where it existed instead.

Link to the last commit where xdg-app-helper.c existed

---

meson.build

This follows the usual feature semantics: they're mandatory if the
feature is enabled, aren't checked if the feature is disabled, and are
optional if the feature is in the auto state (which is the default for
this particular feature).
The logic used here is similar to AX_CHECK_DOCBOOK_XSLT in
autoconf-archive.
Resolves: https://github.com/containers/bubblewrap/issues/500

build: Auto-detect presence of Docbook XSL stylesheets

---

.github/workflows/check.yml
tests/meson.build
tests/test-specifying-pidns.sh

* tests: Disable sanitizers for try-syscall
gcc's AddressSanitizer makes system calls that our filter doesn't
allow for, resulting in a fatal error when run under a restrictive
seccomp filter.
try-syscall is a helper for the test, rather than being code under test
itself, so we don't really need this instrumentation in it: all we want
it to do is make some specific syscalls.
* tests: Disable leak detection when joining user-specified pid namespace
If we don't do this, AddressSanitizer busy-loops with this backtrace:
#0  in sched_yield
#1  in __sanitizer::StopTheWorld
#2  in __lsan::LockStuffAndStopTheWorldCallback
#3  in __GI___dl_iterate_phdr
#4  in __lsan::LockStuffAndStopTheWorld
#5  in __lsan::CheckForLeaks
#6  in __lsan::DoLeakCheck
#7  __lsan::DoLeakCheck
#8  in __cxa_finalize
#9 …

tests: Better compatibility with gcc/clang sanitizers

---

tests/try-syscall.c
utils.h

This change would be useful for the [Steam container runtime](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/master/docs/container-runtime.md), to avoid having to patch the bundled copy of bubblewrap to be able to use it as a subproject.

Allow building on old glibc without PR_SET_CHILD_SUBREAPER defined

---

tests/try-syscall.c

_MIPS_SIM_ABI32 etc. are defined by Linux <asm/sgidefs.h>, which is
included by glibc <sys/syscall.h> (which defers to Linux headers to
get syscall numbers), but not by musl <sys/syscall.h>.
_ABIO32 etc. are predefined by the compiler, so they are always
available, regardless of libc. References:
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=27d54b2a6c18ef1ae50f1a5b432d590438445b90
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=0ea339ea4d9c3e04ae17da6bf389617eb0251e57

try-syscall: Use compiler-predefined macros to detect mips ABI

---

.github/workflows/check.yml
meson.build
meson_options.txt
tests/use-as-subproject/assert-correct-rpath.py
tests/use-as-subproject/meson.build

This is useful when building a self-contained, relocatable tree
containing a build of bubblewrap and all of its non-glibc dependencies
(in practice this means libcap and maybe libselinux), as is done in
the Steam container runtime. A RPATH/RUNPATH pointing to ${ORIGIN}/../lib
allows bwrap to find an adjacent, bundled copy of libcap.

meson: Add options to set a RPATH/RUNPATH on the bwrap executable

---

tests/test-run.sh

* test-run: Skip a test if we can read /etc/shadow
Ordinarily, we would not be able to read /etc/shadow if we're not uid 0;
but when building in a sysroot owned by the current user (for example
by setting it up using bwrap, as steam-runtime-tools does), we might
actually be able to read it. Skip the assertion that we cannot read it
in this case.
* test-run: Add another assertion that we cannot read /etc/shadow
The goal of this assertion was to demonstrate that a setuid bwrap does
not give us access to otherwise unreadable files, but if we want to
check that, we should probably be looking at the bind-mount destination
instead of the source file.
Leave the old assertion in too, just in case *that* fails.
---
@RyuzakiKK will probably find this useful.

Adjust tests related to /etc/shadow

---

bind-mount.c
bind-mount.h
bubblewrap.c

Prompted by flatpak/flatpak#4731, in which a misconfigured SMB automount
was failing to be remounted with ENODEV. This would have been easier to
debug if we knew which path could not be remounted.
---
This is basically a continuation of #434.

bind-mount: Include failing path in error message

---

tests/test-run.sh

`command -v` is the standardized replacement for `which` and never writes to stderr
Signed-off-by: a1346054 <36859588+a1346054@users.noreply.github.com>

test-run: replace nonstandard `which`

---

bubblewrap.c

In particular, this would have given #371 a clearer error message.

Improve error message when clone() fails with ENOSPC

---

bubblewrap.c
bwrap.xml
completions/bash/bwrap
completions/zsh/_bwrap
tests/test-run.sh

`bwrap` is a sandboxing utility, and one usually sandboxes a process to control its access to resources. One of the resources that one might want to control is disk space usage, but `bwrap` currently provides no facilities to control disk space usage.
We're using `bwrap` for [a programming language playground](https://github.com/tomsmeding/pastebin-haskell/tree/play) where people can submit arbitrary code; we run the code on a server and send the output back. Obviously this needs sandboxing, and among other things, we want to avoid an ENOSPC DOS.
#375 suggested a possible fix for this missing feature: to add a facility to control the size of a created `tmpfs`.
Fixes #375.
This adds a new `--size` option that works similarly to `--perms` in that it modifies a subsequent `--tmpfs` option. …

Add --size option to control size of a --tmpfs

---

configure.ac

AS_IF is best-practice for Autoconf, because it resolves conditional
dependencies correctly; for example, if the first use of
PKG_CHECK_MODULES is inside an if/then/fi block, then
PKG_CHECK_PKG_CONFIG will also be conditional, but if the first use of
PKG_CHECK_MODULES is inside AS_IF, then PKG_CHECK_PKG_CONFIG will be
done unconditionally.

build: Consistently use AS_IF instead of if/then/fi

---

tests/test-run.sh

* test-run: If bubblewrap is setuid, assert that --size is not allowed
Previously, this test would have failed for a setuid bubblewrap.
* test-run: Don't rely on df supporting the --output=size option
df --output was new in coreutils 8.21 (2013), and non-GNU
implementations like busybox df don't have it.
This avoids a test failure in Steam Runtime 1 'scout', which is based
on Ubuntu 12.04 (2012). It'll also be helpful for anyone maintaining
an OS with non-GNU shell utilities.
cc @RyuzakiKK @tomsmeding

Fix test failures in 0.7.0 on unusual platforms

---

bubblewrap.c
bwrap.xml
completions/bash/bwrap
completions/zsh/_bwrap
tests/test-run.sh

* Add an option to disable nested user namespaces by setting limit to 1
Some use-cases of bubblewrap want to ensure that the subprocess can't
further re-arrange the filesystem namespace, or do other more complex
namespace modification. For example, Flatpak wants to prevent sandboxed
processes from altering their /proc/$pid/root/.flatpak-info, so that
/.flatpak-info can safely be used as an indicator that a process is part
of a Flatpak app.
This approach was suggested by lukts30 on containers/bubblewrap#452.
The sysctl-controlled maximum numbers of namespaces are themselves
namespaced, so we can disable nested user namespaces by setting the
limit to 1 and then entering a new, nested user namespace. The resulting
process loses its privileges in the namespace where the limit was set
to 1, so …

Add an option to disable nested user namespaces by setting limit to 1

---

tests/test-run.sh

Older versions of capsh would only show the capabilities, which we expect not to change when we don't drop capabilities; but newer versions also display whether the NO_NEW_PRIVS bit is set, and we *do* expect to change that.
Resolves: https://github.com/containers/bubblewrap/issues/544

test-run: Filter out no-new-privs in capsh output

---

bubblewrap.c

General-purpose desktop distributions are compiled with CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER, but vendor kernels for phones and other assorted embedded devices don't necessarily enable these options. These kernels are unsuitable for running Flatpak, or anything else that relies on `bwrap --seccomp` or `bwrap --add-seccomp-fd`.
Missing CONFIG_SECCOMP or CONFIG_SECCOMP_FILTER is not the *only* reason why we could get EINVAL here: I think we'd also get EINVAL if the seccomp program is syntatically invalid. However, it's a relatively likely reason, so it seems worth providing a hint.
Helps: flatpak/flatpak#3069

Attempt to clarify error message for missing CONFIG_SECCOMP_FILTER

---

bwrap.xml

Mention how to format capabilities for --add-cap, e.g. CAP_DAC_READ_SEARCH instead of DAC_READ_SEARCH.

bwrap.1: mention example format of capability

---

utils.c

load_file_at() is affected in the error case, since all other current callers call die_with_error() before closing the passed file descriptor.
Found by GCC analyzer:
./utils.c: In function ‘load_file_at’:
./utils.c:630:3: warning: double ‘close’ of file descriptor ‘fd’ [CWE-1341] [-Wanalyzer-fd-double-close]
630 |   close (fd);
|   ^~~~~~~~~~
‘load_file_at’: events 1-4
|
|  616 | load_file_at (int         dirfd,
|      | ^~~~~~~~~~~~
|      | |
|      | (1) entry to ‘load_file_at’
|......
|  624 |   if (fd == -1)
|      |      ~
|      |      |
|      |      (2) following ‘false’ branch (when ‘fd != -1’)...
|......
|  627 |   data = load_file_data (fd, NULL);
|      |   ~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~
|      |   |      |
|      |   |      (4) calling ‘load_file_data’ from ‘load_file_at’ …

load_file_data: do not close fd on error to avoid double-close

---

README.md
SECURITY.md

bubblewrap can provide a robust security boundary that severely limits functionality, or it can provide full functionality without any attempt at being a security boundary, or anything in between those extremes. If a caller of bubblewrap chooses inappropriate command-line arguments for their desired security model, then bubblewrap will not provide the security model they are aiming for, but this is not a bubblewrap vulnerability.
Apparently this isn't clear to everyone, so try to clarify.
The one place where bubblewrap *does* define some sort of security policy for itself is when it's setuid root, in which case it's responsible for preventing users from carrying out privilege escalation attacks like CVE-2020-5291.
Resolves: https://github.com/containers/bubblewrap/issues/555
--- …

README, SECURITY: Clarify that bubblewrap does not define a security model

---

README.md

Hi!
This is the first piece aimed at improving on the #555 situation. I'm looking forward to your review :beers: 
~PS: The addition of the tip on brace expansion is unrelated. I can drop it or extract a new pull request for it as needed, as you like.~

Improve readme with regard to --new-session security (related to #555)

---

tests/test-run.sh

* tests: Explicitly unshare userns when testing --disable-userns
If we're running the tests as uid 0 with capabilities, then bwrap will
not create a new user namespace by default, which means the limit won't
be exceeded and the test will fail. Make sure we always try to create
the new user namespace.
* tests: Try harder to evade --disable-userns
The worst-case scenario in terms of enforcing --disable-userns is that
we're retaining all capabilities, so test that too, to make sure that
the option is genuinely restricting even a privileged user.
---
The first commit is a 0.8.0 release blocker for me (although I could apply it as a downstream Debian patch if necessary), the second is just a nice-to-have for more thorough test coverage.
cc @alexlarsson @cgwalters

Fix test failure since #488 when running as uid 0

---

bubblewrap.c
bwrap.xml
completions/bash/bwrap
completions/zsh/_bwrap
tests/test-run.sh

Fixes containers/bubblewrap#91
Add the ability to overwrite argv[0] when starting a process in a container. Using --argv0 to be consistent with ld.so --argv0.
Overwriting argv[0] is useful as some tools change their behavior based on the value of argv[0]. For example, when bash is symlinked to sh it behaves as sh. Similarly, unxz is a symlink to xz and changes the default from compressing to decompressing. An extreme example is on many systems, date, df, cat and so on are all symlinks to the coreutils binary.
Example usage:
```
bwrap --bind / / --argv0 sh bash
```
PS: Thank you for the kind advice on my [previous pull-request to add a --exec option](https://github.com/containers/bubblewrap/pull/597).

Add --argv0 option

---

bubblewrap.c
utils.c
utils.h

We already have `get_oldroot_path` in utils, so let's be consistent about this.

utils: Move get_newroot_path to utils

---

tests/test-run.sh

The test wants to mount /tmp on /mnt but /mnt comes from the host and can be a symlink in which case the test fails. Skip the test in this situation.

tests: Skip test when host /mnt is a symlink

---

tests/test-run.sh

Fixes containers/bubblewrap#420 using the proposed approach of defining ok(), done_testing(), and shifting the TAP plan from being written at the start to being written at the end. I also introduced an ok_skip() function, but I'm happy to change all uses to ok "# SKIP ..." if you prefer that.
This pull request also has two trivial fixes to the tests: 
1. A typo in a test case ("prefxing" -> "prefixing"
2. Switch the last /bin/bash to just bash (there are five references to bash, the other four--including #!/usr/bin/env bash-- all use the bash on the $PATH)
Let me know if you'd rather these two changes were in separate pull requests.

Implement change proposed in "All MRs that add unit tests conflict with each other"

---

tests/libtest.sh

The "can pivot to new rootfs recursively" test is the only test that fails due to the quirks of NixOS. Specifically, NixOS does not have /lib or /sbin directories. To fix, I've made /lib and /sbin --ro-bind-try instead of --ro-bind.
Adding --ro-bind-try /nix/store /nix-store as findmnt is located there. As this is the only use of findmnt in the tests, we could also use an alternative way to check if /usr has been mounted in the container.
As NixOS is out of step with mainstream Linux distros, I understand if bubblewrap doesn't want to support it for it's tests.

Make test "can pivot to new rootfs recursively" work on NixOS

---

demos/userns-block-fd.py

This version of python reached its EOL in March 2019.

Drop support for Python<3.4 in demo code

---

bind-mount.c
bubblewrap.c
utils.c
utils.h

* utils: Give warnv() the ability to log strerror() or similar
This lets die_with_error() reuse it.
* utils: Add a specialized function to print errno for mount(2)
mount(2) uses ENOSPC to represent an arbitrary anti-denial-of-service
limit being exceeded, which is outside the usual meaning of
"No space left on device". We can make this clearer by catching that
particular failure mode and giving users a hint.
Reference: https://bugzilla.kernel.org/show_bug.cgi?id=218336  
Resolves: https://github.com/ValveSoftware/steam-runtime/issues/637
cc @RyuzakiKK

Show a better error message for mount(2) -> ENOSPC

---

bubblewrap.c

When creating symlinks specified with --symlink, check errno if creation fails. If the reason was EEXIST, check the path of the existing symlink. If it matches what was desired, continue as normal.

Make --symlink idempotent

---

README.md

Rebased and re-worded version of #370, resolving conflicts with #560. Co-authored-by: @brandsimon.

Document some potential pitfalls in sandboxing

---

Makefile.am

From: @frobnitzem
The manual rule for test-bwrap in Makefile-bwrap.in threw a warning because automake [renames the target of things in TESTS](https://www.gnu.org/software/automake/manual/html_node/Extending.html).
[smcv: Split out from a larger commit, re-worded commit message]

Silence Automake warning for items in TESTS being renamed

---

bind-mount.c
bubblewrap.c
utils.c
utils.h

* Rework xcalloc
Pass the first parameter to calloc(3) to perform the overflow check.
* Avoid undefined behavior in realloc
Passing a NULL pointer and a size of 0 is currently implementation defined behavior[1] and will become (with C23) undefined behavior[2].
[1]: https://manpages.debian.org/unstable/manpages-dev/realloc.3.en.html
[2]: https://en.cppreference.com/w/c/memory/realloc

Allocation improvements

---

.github/workflows/check.yml

Reference: https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

workflows: Upgrade codeql-action to v2

---

utils.c

The size to be allocated is tracked as ssize_t, so if it's larger than this, doubling it would cause a signed overflow.
Limiting the data we will read into memory to SSIZE_MAX/2 still lets it occupy 25% of addressable memory (1 GiB on 32-bit or some very large amount on 64-bit), which should be adequate. In practice we expect this function to read a few KiB at most.
In practice we're likely to run out of memory before reaching this point; changing this to SSIZE_MAX / 8, compiling as 32-bit and running `${builddir}/bwrap --args 0 < /dev/zero` is a convenient way to test this code path.
Fixes: 422c078e "Check for allocation size overflows"
/cc @cgzones

utils: Don't let ssize_t overflow when reading very large files

---

.github/workflows/check.yml

* workflows: Use upload-artifact@v4
Reference: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
* workflows: Use latest version of actions/checkout
It isn't entirely clear to me what the incompatibilities are, but
hopefully in simple cases like ours it's functionally equivalent.

Update Github Actions configuration

---

tests/test-run.sh

eg. busybox stat only has -c and not --format

tests: use stat -c instead of --format for compatibility

---

meson_options.txt

string values for boolean options should be avoided and will be deprecated in a future version of meson.
Ref https://mesonbuild.com/Release-notes-for-1-1-0.html

meson: use boolean value for boolean options

---

bind-mount.c
bubblewrap.c
bwrap.xml
tests/test-run.sh
utils.c
utils.h

* test-run: Assert that repeating --chdir logs a warning
This is the case since commit 0d369cd "main: Warn when
non-repeatable options are repeated".
* utils: Put nearly all diagnostic output through a common log function
This takes a syslog-style severity level, allowing us to act based on
the severity.
Take the opportunity to make the `__debug__` macro (which normally expands
to nothing, but can be enabled by changing a `#if 0` to `#if 1`) less
weird and easier to use, by taking it out of the reserved-for-the-compiler
namespace, adding a newline automatically, and not requiring nested
parentheses.
* Add new --level-prefix option
This prepends a syslog-style priority level such as <3> to each line of
diagnostic output, so that the diagnostic output can be parsed by
tools like …

Add new --level-prefix option

---

bind-mount.c
bubblewrap.c
network.c
utils.c
utils.h

* utils: Move TEMP_FAILURE_RETRY reimplementation here
This will allow it to be used in more places.
Helps: https://github.com/containers/bubblewrap/issues/657
* Handle EINTR when doing I/O on files or sockets
If a blocking operation is interrupted by a signal, including SIGCHLD,
various things can fail with EINTR. This is not a "real" error and can
result in spurious failures.
Resolves: https://github.com/containers/bubblewrap/issues/657
cc @refi64 @mcatanzaro

Handle EINTR on blocking I/O

---

utils.c

dirfd() and socket() are POSIX standard library functions, so use dfd and sockfd instead.
---
This fixes build failures with gcc 4.6 in an Ubuntu 12.04 derivative, but seems like a good cleanup change to make the code easier to understand, even if gcc no longer warns about this particular collision.
Unfortunately this is going to conflict with #659, although the conflict resolution is simple and obvious.
cc @refi64

utils: Avoid shadowing the names of global functions

---

bind-mount.c
bubblewrap.c
tests/test-utils.c
utils.c
utils.h

We don't need to reinvent these, especially in a confusing form (bool type like stdbool.h, but TRUE and FALSE constants like GLib). stdbool.h was available in the gcc 4.6 that is the default compiler in Ubuntu 12.04, more than a decade ago, so it seems sufficiently ubiquitous.
cc @refi64

Use stdbool.h for booleans

---

bubblewrap.c
bwrap.xml
completions/bash/bwrap
tests/test-run.sh
tests/test-utils.c
utils.c
utils.h

This commit adds --overlay, --tmp-overlay, --ro-overlay, and --overlay-src options to enable bubblewrap to create overlay mounts. These options are only permitted when bubblewrap is not installed setuid.
---
This is a continuation/partial rewrite of #167, addressing the feedback given there.
Other improvements of note:
* Tests!
* Characters treated specially by overlayfs are escaped; there are now no (known?) restrictions on the characters that can be in an overlay path.
*  `--tmp-overlay` is a new contribution for a use case I frequently have: I want to mount an overlay that is writable but I don't want to persist the writes between runs.

Add --overlay and related options

---

utils.c

bubblewrap is used in some surprisingly old environments, including version 1 of the Steam Runtime, which has gcc 4.6 or 4.8 as its default compiler (depending on exactly how you define "default"). These very old versions don't support the builtin used here.
cc @refi64 @RyuzakiKK

utils: Add a fallback version of xadd, xmul for ancient gcc

---

utils.c

* utils: Don't assume cmsg data is aligned suitably for struct ucred
As documented in cmsg(3), the alignment of control messages is not
guaranteed, so for portability to architectures with strong alignment
requirements we should memcpy to and from a suitably aligned instance
of the desired data structure on the stack.
Helps: https://github.com/containers/bubblewrap/issues/637
* utils: Ensure that the buffer for struct cmsghdr is suitably-aligned
A char array on the stack is not guaranteed to have any particular
alignment.
Resolves: https://github.com/containers/bubblewrap/issues/637
cc @mcatanzaro @refi64

Ensure correct alignment when dealing with control messages

---

completions/bash/meson.build

Before Meson 1.3.0, this would not do what we meant (instead defining prefix to a wrong value composed from the remaining arguments).
The only reason we needed to redefine prefix in the first place is that bash-completion older than 2.10 did not allow users of its pkg-config file to override the datadir used to compute its completionsdir, but that was addressed in version 2.10 (2019). Users of older bash-completion should set bubblewrap's bash_completion_dir build option, if the automatically-discovered default is not appropriate.
Related to https://github.com/containers/bubblewrap/issues/609
/cc @refi64 @eli-schwartz

completions: Don't try to define more than one variable for pkg-config
